name: Slack Notifier

on:
  schedule:
    - cron:  '45 7 * * 1-5'
  workflow_dispatch:

#  push:
#    branches:
#      - master

jobs:
  slacknotifier:
    runs-on: ubuntu-latest
    name: Slack Notifier
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv

      -   uses: actions/checkout@v2

      -   name: Composer install
          run: composer install --ansi --prefer-dist --no-interaction --no-progress --quiet

      -   name: Write env file
          run: |
              echo 'GH_TOKEN='${{ secrets.GH_TOKEN }} > .env && \
              echo 'SLACK_TOKEN='${{ secrets.SLACK_TOKEN }} >> .env && \
              echo 'SLACK_CHANNEL_CORE='${{ secrets.SLACK_CHANNEL_CORE }} >> .env && \
              echo 'SLACK_CHANNEL_QA='${{ secrets.SLACK_CHANNEL_QA }} >> .env

      -   name: Execute script
          run: php bin/console slack:notifier