<?php

namespace Console\App\Service\PrestaShop;

class RepositoryNameConverter
{
    private const REPOSITORIES_MAPPING = [
        // tools and libs
        'core-weekly-generator' => 'Core Weekly Generator tool',
        'CsaGuzzleBundle' => 'CsaGuzzle Bundle (fork)',
        'docker' => 'Docker images',
        'docker-ci' => 'PrestaShop on Docker',
        'docker-internal-images' => 'Docker internal images',
        'docs' => 'Changes in developer documentation sources',
        'devdocs-site' => 'Changes in developer documentation site',
        'ga.tests.ui.pr' => 'Automated tests on Pull Requests',
        'ps-docs-theme' => 'Changes in developer documentation theme',
        'php-coding-standards' => 'PHP Coding Standards',
        'php-dev-tools' => 'PHP Developer Tools',
        'prestashop-ui-kit' => 'Prestashop UI Kit',
        'QANightlyResults' => 'QA nightly results',
        'TranslationFiles' => 'Translation Files repository',
        'TranslationToolsBundle' => 'TranslationTools Bundle',
        'vagrant' => 'PrestaShop Virtual Machine',
        'decimal' => 'Decimal',
        'example-modules' => 'Example modules',
        'example_module_mailtheme' => 'Mail theme example',
        'PrestaShop-modules' => 'PrestaShop modules registry',
        'issuebot' => 'Issues Bot',
        'PrestaShop-webservice-lib' => 'Webservices PHP Client',
        'stylelint-config' => 'stylelint configuration',
        'eslint-config' => 'eslint configuration',
        'jquery.live-polyfill' => 'jQuery Live Polyfill library',
        'stylelint-browser-compatibility' => 'Stylelint browser compatibility plugin',
        'mjml-theme-converter' => 'MJML Theme Converter',
        'circuit-breaker' => 'Circuit Breaker',
        // modules
        'autoupgrade' => 'Auto Upgrade module',
        'blockreassurance' => 'Customer reassurance block module',
        'blockwishlist' => 'Wishlist block module',
        'contactform' => 'Contact Form module',
        'cronjobs' => 'Cronjobs module',
        'dashactivity' => 'Dashboard Activity module',
        'dashgoals' => 'Dashboard Goals module',
        'dashproducts' => 'Dashboard Products module',
        'dashtrends' => 'Dashboard Trends module',
        'distribution-api' => 'Distribution API',
        'gadwords' => 'Google Ads module',
        'gamification' => 'Gamification module',
        'gridhtml' => 'Simple HTML table display module',
        'gsitemap' => 'Google Sitemap module',
        'graphnvd3' => 'NVD3 Charts module',
        'nightly-board' => 'Nightly board',
        'pagesnotfound' => 'Pages not found module',
        'productcomments' => 'Product Comments module',
        'ps_banner' => 'Banner module',
        'ps_buybuttonlite' => 'Buy button lite module',
        'ps_cashondelivery' => 'Cash on delivery module',
        'ps_categoryproducts' => 'Products in the same category module',
        'ps_categorytree' => 'Category tree links module',
        'ps_checkpayment' => 'Check payment module',
        'ps_contactinfo' => 'Contact informations module',
        'ps_crossselling' => 'Cross-selling module',
        'ps_currencyselector' => 'Currency selector',
        'ps_customeraccountlinks' => 'Customer account links module',
        'ps_customersignin' => 'Customer "Sign in" link module',
        'ps_customtext' => 'Custom text module',
        'ps_dataprivacy' => 'Customer data privacy block module',
        'ps_faviconnotificationbo' => 'Order Notifications on the Favicon module',
        'ps_emailalerts' => 'Email Alerts module',
        'ps_emailsubscription' => 'Email subscription module',
        'ps_facetedsearch' => 'Faceted search module',
        'ps_featuredproducts' => 'Featured products module',
        'ps_googleanalytics' => 'Google Analytics module',
        'ps_imageslider' => 'Image slider module',
        'ps_legalcompliance' => 'Legal Compliance',
        'ps_languageselector' => 'Language selector module',
        'ps_linklist' => 'Links list module',
        'ps_livetranslation' => 'Live translation module',
        'ps_mainmenu' => 'Main menu module',
        'ps_newproducts' => 'New Products module',
        'ps_productinfo' => 'Product tooltips module',
        'ps_reminder' => 'Reminder module',
        'ps_searchbar' => 'Search Bar module',
        'ps_searchbarjqauto' => 'Search bar autocomplete module',
        'ps_sharebuttons' => 'Share Buttons module',
        'ps_shoppingcart' => 'Shopping cart module',
        'ps_socialfollow' => 'Social Follow module',
        'ps_themecusto' => 'Theme customization module',
        'ps_wirepayment' => 'Wire payment module',
        'pscleaner' => 'PrestaShop Cleaner module',
        'ps_supplierlist' => 'Suppliers list module',
        'psgdpr' => 'GDPR module',
        'sekeywords' => 'Search engine keywords statistics module',
        'statsbestcategories' => 'Best categories statistics module',
        'statsbestcustomers' => 'Best customers statistics module',
        'statsbestmanufacturers' => 'Best manufacturers statistics module',
        'statsbestproducts' => 'Best-selling products statistics module',
        'statsbestsuppliers' => 'Best suppliers statistics module',
        'statsbestvouchers' => 'Best vouchers statistics module',
        'statscarrier' => 'Carrier distribution statistics module',
        'statscatalog' => 'Catalog statistics module',
        'statscheckup' => 'Catalog evaluation statistics module',
        'statsdata' => 'Data mining for statistics module',
        'statsequipment' => 'Browsers and operating systems statistics module',
        'statsforecast' => 'Stats Dashboard module',
        'statslive' => 'Visitors online statistics module',
        'statsnewsletter' => 'Newsletter statistics module',
        'statsorigin' => 'Visitors origin statistics module',
        'statspersonalinfos' => 'Registered customer information statistics module',
        'statsproduct' => 'Product details statistics module',
        'statsregistrations' => 'Registrations statistics modules',
        'statssales' => 'Sales and orders statistics module',
        'statssearch' => 'Shop search statistics module',
        'statsstock' => 'Available quantities statistics module',
        'statsvisits' => 'Visits and Visitors statistics module',
        'vatnumber' => 'European VAT number module',
        'watermark' => 'Watermark module',
        'welcome' => 'OnBoarding module',
        'ps_carriercomparison' => 'Carriers comparison module',
        'ps_qualityassurance' => 'Quality Assurance module',
        'ps_brandlist' => 'Brands list module',
        'ps_advertising' => 'Advertising module',
        'ps_viewedproduct' => 'Viewed products block module',
        'ps_bestsellers' => 'Best sellers module',
        'paymentexample' => 'Payment example module',
        'ps_specials' => 'Special offers module',
        // themes
        'hummingbird' => 'Hummingbird theme',
        'classic-theme' => 'Classic theme',
        // misc
        'ADR' => 'Architecture Decision Records repository',
        'classic-rocket' => 'Classic-rocket theme',
        'prestashop-specs' => 'PrestaShop Specifications',
        'prestonbot' => 'PrestonBot',
        'traces' => 'Traces',
        'TopContributors' => 'PrestaShop contributors website',
        'open-source' => 'The PrestaShop open source project',
        'ps-org-theme' => 'Theme for the PrestaShop open source project website',
        'test-scenarios' => 'PrestaShop test scenarios',
        'php-ps-info' => 'PrestaShop PHP Informations Tool',
        'user-documentation-landing' => 'User documentation landing page',
        'phpstan-prestashop' => 'PrestaShop PHPStan extension',
        'contextual-help-api' => 'Contextual Help API',
        'psssst' => 'Module analyzer',
        'ps-project-metrics' => 'PrestaShop Project Metrics',
        'ps_distributionapiclient' => 'Distribution API Client',
        'ps-monitor-module-releases' => 'Module Releases Monitor',
    ];

    public function __construct()
    {
        return;
    }

    public static function getName($repository)
    {
        if (isset(static::REPOSITORIES_MAPPING[$repository])) {
            return static::REPOSITORIES_MAPPING[$repository];
        }

        return $repository;
    }
}
